apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-notification-secrets
  namespace: monitoring
type: Opaque
stringData:
  slack-webhook-url: https://hooks.slack.com/services/REPLACE_ME
  pagerduty-routing-key: REPLACE_ME
