apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 15s
      honorLabels: true
      path: /metrics
      scheme: http
  jobLabel: falco
  selector:
    matchLabels:
      app.kubernetes.io/name: falco
      app.kubernetes.io/instance: falco
      type: falco-metrics
  namespaceSelector:
    matchNames:
      - falco
