apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-capabilities
  annotations:
    policies.kyverno.io/title: Restrict Capabilities
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: restrict-capabilities
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - argocd
                - karpenter
                - istio-system
                - cilium-secrets
                - cert-manager
                - monitoring
                - observability
                - logging
                - falco
      validate:
        message: >-
          Adding capabilities beyond NET_BIND_SERVICE is not allowed.
        pattern:
          spec:
            =(ephemeralContainers):
              - =(securityContext):
                  =(capabilities):
                    =(add):
                      - NET_BIND_SERVICE
            =(initContainers):
              - =(securityContext):
                  =(capabilities):
                    =(add):
                      - NET_BIND_SERVICE
            containers:
              - =(securityContext):
                  =(capabilities):
                    =(add):
                      - NET_BIND_SERVICE
