apiService:
  create: true

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 400Mi
