global:
  meshID: gradyent-prod
  multiCluster:
    clusterName: gradyent-prod

meshConfig:
  enableAutoMtls: true
  enableTracing: true
  defaultConfig:
    tracing: {}
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
  extensionProviders:
    - name: zipkin
      zipkin:
        service: jaeger-collector.observability.svc.cluster.local
        port: 9411

pilot:
  autoscaleEnabled: true
  autoscaleMin: 2
